{% raw %}{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.global.prefix }}-ingress
  annotations:
    {{- if .Values.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.certManager.clusterIssuerName }}
    {{- end }}
    {{- if eq .Values.ingress.controller "traefik" }}
    {{- if .Values.traefik.createMiddleware }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.traefik.middleware.namespace }}-{{ .Values.traefik.middleware.name }}@kubernetescrd
    {{- end }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.controller }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.global.prefix }}-tls
      hosts:
        - {{ .Values.domain }}
  {{- end }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /{% endraw %}{{ cookiecutter.api_prefix }}{% raw %}
            pathType: Prefix
            backend:
              service:
                name: {{ include "django-backend.fullname" . }}
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "react-frontend.fullname" . }}
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}{% endraw %}
