apiVersion: v1
kind: Secret
metadata:
  name: {{ include "full-name" . }}-postgresql
  labels:
    app: postgresql
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgresql.database | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgresql.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | b64enc | quote }}
