apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "full-name" . }}-postgresql
  labels:
    app: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
